export const CELSIUS_TO_FAHRENHEIT_RATIO = 9 / 5
export const FAHRENHEIT_OFFSET = 32
export const FINE_DUST_GOOD_MAX = 15
export const FINE_DUST_MODERATE_MAX = 35
export const HOT_WEATHER_THRESHOLD_CELSIUS = 25
export const JAVASCRIPT_MONTH_OFFSET = 1
export const MINIMUM_PM25 = 0
export const WEATHER_STATISTICS_DECIMAL_PLACES = 1
